version: "2.1"
services:
  api:
    image: "lnwu/todo-api-staging:${BUILDKITE_BUILD_NUMBER}"
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
    # volumes:
    #   - ./staging/postgres-data:/var/lib/postgresql/data
